Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2018-03, with the labels that each got.

#60 Remove dependency on custom have_attributes
  spec/support/ansible_shared/automation_manager/job.rb
Labels: test

#59 To store Tower repo last_updated_on
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
  spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source.rb
Labels: enhancement

#65 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#66 Move #retire_now to shared code
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/job.rb
  spec/support/ansible_shared/automation_manager/job.rb
Labels: bug

#63 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#62 Tower Rhv credential type
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/rhv_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/rhv_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
Labels: enhancement

#69 Add host field to rhv_credential
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/rhv_credential.rb
Labels: enhancement

#67 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#68 [GAPRINDASHVILI] Updated translations for gaprindashvili update
  locale/es/ManageIQ_Providers_AnsibleTower.po
  locale/fr/ManageIQ_Providers_AnsibleTower.po
  locale/ja/ManageIQ_Providers_AnsibleTower.po
  locale/pt_BR/ManageIQ_Providers_AnsibleTower.po
  locale/zh_CN/ManageIQ_Providers_AnsibleTower.po
Labels: enhancement

#70 Add vault credential to Ansible Tower Job.
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/job.rb
  spec/support/ansible_shared/automation_manager/job.rb
Labels: enhancement, gaprindashvili/yes
