Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2018-10, with the labels that each got.

#129 queue_refresh_task returns an id array, not objects
  spec/support/ansible_shared/automation_manager/configuration_script.rb
  spec/support/ansible_shared/automation_manager/configuration_script_source.rb
  spec/support/ansible_shared/automation_manager/credential.rb
Labels: test

#101 [GAPRINDASHVILI] Update gettext catalogs for gaprindashvili update
  locale/ManageIQ_Providers_AnsibleTower.pot
Labels: internationalization

#128 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Providers_AnsibleTower.pot
  locale/en/ManageIQ_Providers_AnsibleTower.po
  locale/es/ManageIQ_Providers_AnsibleTower.po
  locale/fr/ManageIQ_Providers_AnsibleTower.po
  locale/ja/ManageIQ_Providers_AnsibleTower.po
  locale/pt_BR/ManageIQ_Providers_AnsibleTower.po
  locale/zh_CN/ManageIQ_Providers_AnsibleTower.po
  zanata.xml
Labels: internationalization

#131 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#133 Travis - change postgres to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes
