Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2018-12, with the labels that each got.

#143 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#144 Change FactoryGirl to FactoryBot
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_workflow_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/credential_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/job_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/workflow_job_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager_spec.rb
  spec/models/manageiq/providers/ansible_tower/provider_spec.rb
  spec/support/ansible_shared/automation_manager.rb
  spec/support/ansible_shared/automation_manager/configuration_script.rb
  spec/support/ansible_shared/automation_manager/configuration_script_source.rb
  spec/support/ansible_shared/automation_manager/credential.rb
  spec/support/ansible_shared/automation_manager/event_catcher/stream.rb
  spec/support/ansible_shared/automation_manager/job.rb
  spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/support/ansible_shared/provider.rb
Labels: dependencies, gaprindashvili/no, hammer/no

#146 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
