Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2018-11, with the labels that each got.

#135 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_AnsibleTower.po
  locale/fr/ManageIQ_Providers_AnsibleTower.po
  locale/ja/ManageIQ_Providers_AnsibleTower.po
  locale/pt_BR/ManageIQ_Providers_AnsibleTower.po
  locale/zh_CN/ManageIQ_Providers_AnsibleTower.po
Labels: internationalization

#134 Tower 3.3 fix: Credential.manager_ref need to be an integer for Tower 3.3
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/credential.rb
  spec/support/ansible_shared/automation_manager/credential.rb
Labels: blocker, bug, hammer/yes

#138 Credential.manager_ref need to be an integer for Tower 3.3
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/configuration_script_source.rb
  spec/support/ansible_shared/automation_manager/configuration_script_source.rb
Labels: blocker, bug, hammer/yes

#137 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#139 [Changelog] Update for Sprint 98 and G-6
  CHANGELOG.md
Labels: documentation

#141 [HAMMER] [Changelog] Update for Hammer RC-1
  CHANGELOG.md
Labels: documentation

#140 Tower 3.3 removed result_stdout from project_update
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
  manageiq-providers-ansible_tower.gemspec
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/support/tower_data.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_configuration_script_source.yml
Labels: bug

#142 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
