Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2018-07, with the labels that each got.

#105 AnsibleTowerClient::Api.new now requires a version as of v0.16.0
  spec/support/ansible_shared/automation_manager/job.rb
Labels: bug

#106 tower_api.update_in_provider to remove miq_task_id from params
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/tower_api.rb
  spec/support/ansible_shared/automation_manager/configuration_script_source.rb
  spec/support/ansible_shared/automation_manager/credential.rb
Labels: bug

#82 Populate project without update job in Tower
  lib/tasks_private/spec_helper.rake
Labels: pending core

#92 Collect variable Tower data upon population
  lib/tasks_private/spec_helper.rake
Labels: unmergeable

#72 Get stdout on ansible repository refresh
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher.yml
Labels: enhancement

#114 FIX wrong VCR cassette for Embedded Ansible refresher spec
  spec/support/ansible_shared/automation_manager/refresher.rb
Labels: bug

#115 For changes in Ansible Tower client gem
  spec/support/ansible_shared/automation_manager/job.rb
Labels: test
