Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2018-08, with the labels that each got.

#117 Graph refresh of configuration_scripts and configuration_workflows in one InventoryCollection
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
  spec/support/ansible_shared/automation_manager/configuration_workflow.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher.yml
Labels: bug, test

#116 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation

#93 Extract variable Tower data from tests
  lib/tasks_private/spec_helper.rake
  spec/support/ansible_shared/automation_manager/event_catcher/stream.rb
  spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/support/ansible_shared/tower_data_helper.rb
  spec/support/tower_data.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_configuration_script_source.yml
Labels: enhancement, test

#103 Support for Tower Workflow Job.
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/workflow_job.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/workflow_job/status.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_workflow_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/workflow_job_spec.rb
Labels: enhancement

#118 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#122 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation
