Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2019-09, with the labels that each got.

#183 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#186 [WIP] unsharing some shared ansible tower code
  app/models/manageiq/providers/ansible_tower/automation_manager/amazon_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/azure_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configured_system.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/event_catcher/stream.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/event_parser.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/google_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/job.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/machine_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/network_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/openstack_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/refresher.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/rhv_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/satellite6_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/scm_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/vault_credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/vmware_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/amazon_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/azure_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/configuration_script.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/configuration_workflow.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/configured_system.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/event_catcher/stream.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/event_parser.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/google_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/job.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/machine_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/network_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/openstack_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/refresher.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/rhv_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/satellite6_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/scm_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/vault_credential.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/vmware_credential.rb
Labels: wip

#187 Unsharing previously shared ansible tower code
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/credential.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/job/status.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/job/status_mixin.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/tower_api.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/workflow_job/status.rb
  app/models/manageiq/providers/ansible_tower/inventory/collector/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/inventory/parser/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/provider.rb
  app/models/manageiq/providers/ansible_tower/shared/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/collector/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/shared/provider.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
Labels: cleanup

#189 Unshare inventory collector target_collection
  app/models/manageiq/providers/ansible_tower/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/collector/target_collection.rb
  spec/support/ansible_shared/automation_manager/refresh_targeted.rb
Labels: cleanup

#190 fix some specs to make them meaningful
  spec/support/ansible_shared/automation_manager/refresh_targeted.rb
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/configuration_script_sources_in_batches.yml
Labels: bug, cleanup, test

#191 Unshare specs and cleanups
  spec/factories/automation_manager.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_workflow_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/credential_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/job/status_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/job_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_configuration_script_source_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_spec.rb
  spec/models/manageiq/providers/ansible_tower/provider_spec.rb
  spec/spec_helper.rb
  spec/support/ansible_shared/automation_manager/configuration_script.rb
  spec/support/ansible_shared/automation_manager/configuration_script_source.rb
  spec/support/ansible_shared/automation_manager/configuration_workflow.rb
  spec/support/ansible_shared/automation_manager/credential.rb
  spec/support/ansible_shared/automation_manager/event_catcher/stream.rb
  spec/support/ansible_shared/automation_manager/job.rb
  spec/support/ansible_shared/automation_manager/job/status.rb
  spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source.rb
  spec/support/ansible_shared/automation_manager/refresh_targeted.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/support/ansible_shared/provider.rb
  spec/support/ansible_shared/tower_data_helper.rb
  spec/support/vcr_helper.rb
Labels: cleanup, test

#195 [event_parser.rb] Properly filter events
  app/models/manageiq/providers/ansible_tower/automation_manager/event_parser.rb
Labels: bug
