Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2019-05, with the labels that each got.

#170 Improvement to Ansible Tower template runner.
  app/models/manageiq/providers/ansible_tower/automation_manager/template_runner.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/template_runner_spec.rb
Labels: enhancement, hammer/no

#171 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#172 Change plugin common methods to class methods
  lib/manageiq/providers/ansible_tower/engine.rb
Labels: refactoring

#173 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test
