Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2019-10, with the labels that each got.

#198 Add DDF based verify_credentials
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/provider.rb
Labels: enhancement

#194 [HAMMER][event_parser.rb] Filter out extra_vars data
  app/models/manageiq/providers/ansible_tower/shared/automation_manager/event_parser.rb
Labels: bug

#200 Remove zanata.xml
  zanata.xml
Labels: cleanup

#199 Remove zanata from readme
  README.md
Labels: cleanup

#201 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
