Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2019-01, with the labels that each got.

#149 Remove duplicated persister shared_options
  app/models/manageiq/providers/ansible_tower/inventory/persister.rb
Labels: refactoring

#150 Add test cases for Ansible Tower job retireable? method.
  spec/models/manageiq/providers/ansible_tower/automation_manager/workflow_job_spec.rb
  spec/support/ansible_shared/automation_manager/job.rb
Labels: blocker, bug, hammer/yes

#151 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation
