Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2019-02, with the labels that each got.

#153 Targeted refresh
  app/models/manageiq/providers/ansible_tower/automation_manager/refresher.rb
  app/models/manageiq/providers/ansible_tower/inventory.rb
  app/models/manageiq/providers/ansible_tower/inventory/collector.rb
  app/models/manageiq/providers/ansible_tower/inventory/collector/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ansible_tower/inventory/parser.rb
  app/models/manageiq/providers/ansible_tower/inventory/parser/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister/definitions/automation_collections.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister/target_collection.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/collector/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/shared/inventory/parser/configuration_script_source.rb
  config/settings.yml
  lib/tasks_private/spec_helper.rake
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_spec.rb
  spec/support/ansible_shared/automation_manager/refresh_configuartion_script_source.rb
  spec/support/ansible_shared/automation_manager/refresh_targeted.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
  spec/support/tower_data.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/configuration_script.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/configuration_script_sources_in_batches.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/configuration_workflow.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/configured_system.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/credential.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted/inventory_root_group.yml
  spec/vcr_cassettes/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_configuration_script_source.yml
Labels: enhancement

#160 Fix of Inventory and ConfigurationScript model_classes
  app/models/manageiq/providers/ansible_tower/inventory/persister/definitions/automation_collections.rb
  spec/support/ansible_shared/automation_manager/refresh_targeted.rb
  spec/support/ansible_shared/automation_manager/refresher.rb
Labels: bug

#155 Changed provider zone when EMS paused/resumed
  app/models/manageiq/providers/ansible_tower/shared/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/shared/provider.rb
  spec/support/ansible_shared/automation_manager.rb
Labels: enhancement

#161 Remove old ManagerRefresher class
  app/models/manageiq/providers/ansible_tower/automation_manager/refresher.rb
Labels: cleanup

#162 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation
