Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2020-07, with the labels that each got.

#228 Adjusted schema for DDF + validation
  app/models/manageiq/providers/ansible_tower/provider.rb
Labels: enhancement

#229 Delegate authentications= and endpoints= to provider
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/provider.rb
  spec/factories/automation_manager.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/template_runner_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager_spec.rb
Labels: enhancement

#231 Handle a nil manager name better
  app/models/manageiq/providers/ansible_tower/provider.rb
Labels: bug

#230 Dont build object before parsing extra_vars_hash
  app/models/manageiq/providers/ansible_tower/inventory/parser/automation_manager.rb
Labels: bug

#232 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement
