Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2020-10, with the labels that each got.

#239 Delegating zone to provider breaks klass.where(:zone)
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/provider.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresh_worker_spec.rb
Labels: bug

#240 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#222 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-ansible_tower.gemspec
Labels: unmergeable

#241 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
