Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2020-03, with the labels that each got.

#209 Remove inventory_object_refresh from settings
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  config/settings.yml
Labels: cleanup

#210 Address strict partial failures by using explicit Ansible provider factories
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/configuration_workflow_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/job_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/workflow_job_spec.rb
Labels: refactoring, test

#211 Set EMS#enabled in Provider#ensure_managers
  app/models/manageiq/providers/ansible_tower/provider.rb
  spec/support/ansible_shared/automation_manager.rb
Labels: bug

#212 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#213 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#214 remove inventory object refresh
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_spec.rb
Labels: cleanup

#216 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
