Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2020-05, with the labels that each got.

#220 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#221 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#219 Added raw_artifacts to Job
  app/models/manageiq/providers/ansible_tower/automation_manager/job.rb
Labels: enhancement
