Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2021-03, with the labels that each got.

#255 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#258 Fix username and password required error on edit
  app/models/manageiq/providers/ansible_tower/provider.rb
Labels: bug

#252 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-ansible_tower_automation_manager_event_catcher.target
  build/systemd_units/manageiq-providers-ansible_tower_automation_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-ansible_tower_automation_manager_refresh.target
  build/systemd_units/manageiq-providers-ansible_tower_automation_manager_refresh@.service
Labels: technical debt
