Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2022-02, with the labels that each got.

#274 add supports :create for scripts
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/configuration_script_source.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/credential.rb
Labels: enhancement

#276 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-ansible_tower.gemspec
Labels: developer, test

#277 Add Build History Graph to README.md
  README.md
Labels: developer, test

#278 Replace .parent with .module_parent
  app/models/manageiq/providers/ansible_tower/automation_manager/template_runner.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_configuration_script_source_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_spec.rb
  spec/models/manageiq/providers/ansible_tower/automation_manager/refresher_targeted_spec.rb
Labels: rails6.1

#279 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
