Repository ManageIQ/manageiq-providers-ansible_tower, pull requests merged in 2024-02, with the labels that each got.

#303 Drop require_nested
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/event_catcher.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/job.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/refresh_worker.rb
  app/models/manageiq/providers/ansible_tower/automation_manager/workflow_job.rb
  app/models/manageiq/providers/ansible_tower/inventory.rb
  app/models/manageiq/providers/ansible_tower/inventory/collector.rb
  app/models/manageiq/providers/ansible_tower/inventory/parser.rb
  app/models/manageiq/providers/ansible_tower/inventory/persister.rb
Labels: technical debt, rails7

#304 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#305 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#307 delegate `:if` to a symbol
  app/models/manageiq/providers/ansible_tower/automation_manager.rb
Labels: technical debt
